parse: parse.cp parse.h
	g++ -I "/cs/home/ck204/Documents/CS4098/src/inc/libpcap-1.9.0" parse.cp -L/cs/home/ck204/Documents/CS4098/src/inc/libpcap-1.9.0 -lpcap -ldbus-1 -Wall -o parse

clean:
	rm -f *.o
