#!/bin/bash
touch out_fig7test.csv
input="../shortened_input/dartmouth_campus/subset_c"
outfilename=$(date +'%F_%H-%M-%S')
output="${tempdir}/${outfilename}_summary.csv"
tmpdir=$(mktemp -d "../tmp.XXXXXX")
tmpassoc=$(mktemp "${tmpdir}/summarise-associations.XXXXXX.csv")
tmpaps=$(mktemp "${tmpdir}/access-points.XXXXXX.csv")
echo "lines,APs,time" > out_fig7test.csv
#for lines in {100..1000..100}
files=$(find ${input} -name '*.gz')
for FILE in ${files}
do
    (gzip -dc "${FILE}" | parse_associations/parse_tcpdump -) 1>> "${tmpassoc}"
done
lines=400
#do
    step=$(expr ${lines} / 100)
    for n in $(eval echo "{1..${lines}..${step}}")
    do
      for i in {1..20}
      do
        cat ${tmpassoc} | python3 create_test_files.py 1 ${n} ${lines} > temp_associations_${n}AP.csv
        start=$(date +%s)
        matlab -nojvm -nodisplay -nosplash -batch "find_events('temp_associations_${n}AP.csv','${tmpaps}','${output}'); quit" 1>/dev/null
        end=$(date +%s)
        runtime=$(expr $end - $start)
        echo "${lines},${n},$runtime" >> out_fig7test.csv
        rm temp_associations_${n}AP.csv

      done
    done
    rm -r ${tmpdir}
#done
